### ISSUE TITLE
Add support to jhipster 7.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-jooq#9]
The JHipster 7 release is near.
We should add support to it.

jOOQ is broken due to jooq-codegen-maven not been compatible with liquibase 4.
```
Error:  Failed to execute goal org.jooq:jooq-codegen-maven:3.14.8:generate (jooq-codegen) on project jhipster: Execution jooq-codegen of goal org.jooq:jooq-codegen-maven:3.14.8:generate failed: An API incompatibility was encountered while executing org.jooq:jooq-codegen-maven:3.14.8:generate: java.lang.NoSuchMethodError: liquibase.resource.FileSystemResourceAccessor: method 'void <init>()' not found
```

Reverting liquibase to 3.10.3, the application starts correctly.

Details:
https://github.com/jhipster/generator-jhipster-jooq/runs/2117668833?check_suite_focus=true#step:22:193

**Comment by lukaseder** [comment]
Is that something worth fixing in jOOQ? If so, can you please report a bug here? https://github.com/jOOQ/jOOQ/issues/new/choose

**Comment by mshima** [comment]
@lukaseder yep, it was quite late and wanted to give more thought if I'm doing right.

The problem is that liquibase 3 FileSystemResourceAccessor had a empty constructor:
https://github.com/liquibase/liquibase/blob/46fc9ce9ba08806d9ad943983cc99f4f9160aeb7/liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java#L24-L28

While liquibase 4 FileSystemResourceAccessor had a empty constructor:
https://github.com/liquibase/liquibase/blob/7e12c779a78005663611532212649876d5387b04/liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java#L31-L43

My guess is that this is a compiler issue and probably FileSystemResourceAccessor will have to be instantiated dynamically, I will try with 3.15.0-SNAPSHOT and open a bug report there.

**Comment by mshima** [comment]
@lukaseder done https://github.com/jOOQ/jOOQ/issues/11659.
